CREATE DATABASE SISTEMA_KARDEX;
/*CREAMOS LA PRIMERA TABLA PARA LOS ROLES DE USUARIO*/
CREATE TABLE ROLES(
ID_ROL INT PRIMARY KEY IDENTITY(1,1)NOT NULL, 
NOMBRE_ROL VARCHAR(50) NOT NULL UNIQUE,
DESCRIPCION VARCHAR (200) NOT NULL
);
/*CREAMOS LA SEGUNDA TABLA PARA LOS PERMISOS DE USUARIO*/
CREATE TABLE PERMISOS(
ID_PERMISO INT PRIMARY KEY IDENTITY(1,1),
CODIGO_PERMISO VARCHAR(50) NOT NULL UNIQUE,
NOMBRE_PERMISO VARCHAR(200) NOT NULL
);
/*CATEGORIAS*/
CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_CATEGORIA VARCHAR(100)NOT NULL UNIQUE,
DESCRIPCION VARCHAR (200) NOT NULL
);
/*UNIDADES DE MEDIDA*/
CREATE TABLE UNIDADES_MEDIDA(
ID_UNIDAD INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_UNIDAD VARCHAR(100) NOT NULL UNIQUE,
SIMBOLO VARCHAR(10) NOT NULL
);
/*BODEGAS*/
CREATE TABLE BODEGAS(
ID_BODEGA INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_BODEGA VARCHAR(100) NOT NULL UNIQUE,
UBICACION VARCHAR(200) NOT NULL,
ESTADO BIT NOT NULL DEFAULT 1/*0= INACTIVA 1= ACTIVA*/
);
/*TIPOS DE MOVIMIENTOS*/
CREATE TABLE TIPOS_MOVIMIENTOS(
ID_TIPO_MOVIMIENTO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_TIPO VARCHAR(50) NOT NULL UNIQUE,
EFECTO_STOCK SMALLINT NOT NULL
);
/*MOTIVOS DE EXCEPCIONES*/
CREATE TABLE MOTIVOS_EXCEPCIONES(
ID_MOTIVO INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION_MOTIVO VARCHAR(200) NOT NULL UNIQUE
);
/*CREACION DE USUARIOS*/
CREATE TABLE USUARIOS(
ID_USUARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE_COMPLETO VARCHAR(75) NOT NULL,
CORREO VARCHAR(50) NOT NULL UNIQUE,
PASSW_ORD VARCHAR(200) NOT NULL,
ID_ROL INT FOREIGN KEY (ID_ROL)REFERENCES ROLES(ID_ROL)NOT NULL,
ESTADO BIT NOT NULL DEFAULT 1
);
/*ROLES Y PERMISOS*/
CREATE TABLE ROLES_PERMISOS(
ID_ROL INT FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL)NOT NULL,
ID_PERMISO INT FOREIGN KEY(ID_PERMISO)REFERENCES PERMISOS(ID_PERMISO) NOT NULL
);
/*PRODUCTOS*/
CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
CODIGO_UNICO VARCHAR(100) NOT NULL UNIQUE,
DESCRIPCION_PRODUCTO VARCHAR(200) NOT NULL,
ID_CATEGORIA INT FOREIGN KEY (ID_CATEGORIA)REFERENCES CATEGORIAS(ID_CATEGORIA)NOT NULL,
ID_UNIDAD INT FOREIGN KEY (ID_UNIDAD)REFERENCES UNIDADES_MEDIDA(ID_UNIDAD)NOT NULL,
STOCK_MINIMO DECIMAL (18,2)NOT NULL DEFAULT 0.00,
COSTO_PROMEDIO DECIMAL(18,4)NOT NULL DEFAULT 0.0000,
ESTADO BIT NOT NULL DEFAULT 1
);
/*EXISTENCIAS POR BODEGAS*/
CREATE TABLE EXISTENCIAS_BODEGAS(
ID_EXISTENCIA INT PRIMARY KEY IDENTITY(1,1)NOT NULL,
ID_PRODUCTO INT FOREIGN KEY(ID_PRODUCTO)REFERENCES PRODUCTOS(ID_PRODUCTO)NOT NULL,
ID_BODEGA INT FOREIGN KEY(ID_BODEGA)REFERENCES BODEGAS(ID_BODEGA)NOT NULL,
STOCK_ACTUAL DECIMAL(18,2) NOT NULL DEFAULT 0.0000,
CONSTRAINT UQ_PRODUCTO_BODEGA UNIQUE (ID_PRODUCTO, ID_BODEGA)
);
/*MOVIMIENTOS EN EL KARDEX*/
CREATE TABLE MOVIMIENTOS_KARDEX(
ID_MOVIMIENTO INT PRIMARY KEY IDENTITY(1,1)NOT NULL,
FOLIO_COMPROBANTE VARCHAR(50) NOT NULL UNIQUE,
ID_TIPO_MOVIMIENTO INT FOREIGN KEY(ID_TIPO_MOVIMIENTO)REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOVIMIENTO)NOT NULL,
ID_BODEGA_ORIGEN INT NULL,
ID_BODEGA_DESTINO INT NULL,
DOC_REFERENCIA VARCHAR(100)NOT NULL,
ID_MOTIVO INT FOREIGN KEY(ID_MOTIVO)REFERENCES MOTIVOS_EXCEPCIONES(ID_MOTIVO) NULL,
ID_USUARIO_REGISTRO INT NOT NULL,
FECHA_MOVIMIENTO DATETIME NOT NULL DEFAULT GETDATE(),
ESTADO_APROBACION VARCHAR(20) NOT NULL DEFAULT 'APROBADO',
CONSTRAINT CK_ESTADO_MOVIMIENTO 
	CHECK (ESTADO_APROBACION IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'ANULADO')),
ID_USUARIO_AUTORIZA INT NULL,
FECHA_AUTORIZACION DATETIME  NULL,
OBSERVACIONES VARCHAR(500)  NULL,
CONSTRAINT FK_BODEGA_ORIGEN FOREIGN KEY (ID_BODEGA_ORIGEN)REFERENCES BODEGAS(ID_BODEGA),
CONSTRAINT FK_BODEGA_DESTINO FOREIGN KEY (ID_BODEGA_DESTINO)REFERENCES BODEGAS(ID_BODEGA),
CONSTRAINT FK_USUARIO_REGISTRA FOREIGN KEY(ID_USUARIO_REGISTRO)REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT FK_USUARIO_AUROTIZA FOREIGN KEY(ID_USUARIO_AUTORIZA)REFERENCES USUARIOS(ID_USUARIO)
);
/*DETALLE KARDEX*/
CREATE TABLE DETALLE_KARDEX(
ID_DETALLE INT PRIMARY KEY IDENTITY(1,1)NOT NULL,
ID_MOVIMIENTO INT FOREIGN KEY(ID_MOVIMIENTO)REFERENCES MOVIMIENTOS_KARDEX(ID_MOVIMIENTO)NOT NULL,
ID_PRODUCTO INT FOREIGN KEY(ID_PRODUCTO)REFERENCES PRODUCTOS(ID_PRODUCTO) NOT NULL,
CANTIDAD DECIMAL(18,2)NOT NULL,
COSTO_UNITARIO DECIMAL(18,4)NOT NULL,
COSTO_TOTAL DECIMAL (18,4)NOT NULL,
SALDO_ANTERIOR DECIMAL (18,2)NOT NULL,
SALDO_NUEVO DECIMAL(18,2)NOT NULL
);

USE SISTEMA_KARDEX;
DROP DATABASE SISTEMA_KARDEX;